# Diskritasi

## Cari data bertipe numerik (data Klasifikasi )

In [1]:
# mengimpor paket pandas kemudian diberi nama alias pd
import pandas as pd
# untuk menghitung algortima
from math import log2
# mengimpor paket numpy kemudian diberi nama alias np
import numpy as np

In [2]:
# membaca dataset dari url
import pandas as pd

url='https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
c=pd.read_csv(url)
print(c)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [3]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
# Kolom Data
panjang_sepal = c["sepal.length"]
lebar_sepal = c["sepal.width"]
panjang_petal = c["petal.length"]
lebar_petal = c["petal.width"]