# Diskritasi

## Cari data bertipe numerik (data Klasifikasi )

In [2]:
# mengimpor paket pandas kemudian diberi nama alias pd
import pandas as pd
# untuk menghitung algortima
from math import log2
# mengimpor paket numpy kemudian diberi nama alias np
import numpy as np

In [3]:
# membaca dataset dari url
import pandas as pd

url='https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
c=pd.read_csv(url)
print(c)

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
# Kolom Data
panjang_sepal = c["sepal.length"]
lebar_sepal = c["sepal.width"]
panjang_petal = c["petal.length"]
lebar_petal = c["petal.width"]

# Proses diskritisasi dengan equal width dan equal frequency

### Diskritisasi
Diskritisasi digunakan untuk mengubah atribut numerik menjadi atribut kategorikal. Perubahan tersebut dilakukan dengan mengkategorikan atribut numerik menjadi beberapa tingkatan atribut kategorikal. Dalam implementasinya, diskritisasi memiliki dua pendekatan, equal-width intervals dan equal-frequency intervals.

### Equal-width intervals adalah diskritisasi yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar. Fungsi cut digunakan untuk mencari interval menggunakan metode Equal Width Intervals

#### Sepal Width
Equal Width Intervals lebar kelopak bunga Iris

Dikelompokkan menjadi 3 kategori yaitu Kecil, Sedang, dan Lebar

In [6]:
# label kategori Sepal Width
labelK = ["Kecil", "Sedang", "Lebar"]
# Untuk menghitung banyaknya kategori label Sepal Width
jumlahK = len(labelK)

# untuk menghitung interval equal-width
dt_lebarsepal_ew = pd.cut(lebar_sepal, jumlahK, True, labelK)
jumlahdt_kategori_lebarsepal_ew = dt_lebarsepal_ew.value_counts()
jumlahdt_interval_lebarsepal_ew = pd.cut(lebar_sepal, jumlahK, True).value_counts()

In [7]:
# data dari Sepal Width beserta kategorinya
df_lebarsepal_ew=pd.DataFrame(pd.concat((lebar_sepal, dt_lebarsepal_ew), axis = 1))
df_lebarsepal_ew.columns = ["SepalWidth", "category"]
df_lebarsepal_ew

     SepalWidth category
0           3.5   Sedang
1           3.0   Sedang
2           3.2   Sedang
3           3.1   Sedang
4           3.6   Sedang
..          ...      ...
145         3.0   Sedang
146         2.5    Kecil
147         3.0   Sedang
148         3.4   Sedang
149         3.0   Sedang

[150 rows x 2 columns]

In [8]:
#jumlah data Sepal Width berdasarkan kategori
jumlahdt_kategori_lebarsepal_ew

Sedang    88
Kecil     47
Lebar     15
Name: sepal.width, dtype: int64

In [9]:
#jumlah data Sepal Width berdasarkan interval
jumlahdt_interval_lebarsepal_ew

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal.width, dtype: int64

#### Sepal Length
Equal Width Intervals panjang kelopak bunga Iris

Dikelompokkan menjadi 3 kategori yaitu Pendek, Sedang, dan Panjang

In [10]:
# label kategori Sepal Length
labelK = ["Pendek", "Sedang", "Panjang"]
# Untuk menghitung banyaknya kategori label Sepal Length
jumlahK = len(labelK)

# untuk menghitung interval equal-length
dt_panjangsepal_ew = pd.cut(panjang_sepal, jumlahK, True, labelK)
jumlahdt_kategori_panjangsepal_ew = dt_panjangsepal_ew.value_counts()
jumlahdt_interval_panjangsepal_ew = pd.cut(panjang_sepal, jumlahK, True).value_counts()

In [11]:
# data dari Sepal Length beserta kategorinya
df_panjangsepal_ew=pd.DataFrame(pd.concat((panjang_sepal, dt_panjangsepal_ew), axis = 1))
df_panjangsepal_ew.columns = ["SepalLength", "category"]
df_panjangsepal_ew

     SepalLength category
0            5.1   Pendek
1            4.9   Pendek
2            4.7   Pendek
3            4.6   Pendek
4            5.0   Pendek
..           ...      ...
145          6.7   Sedang
146          6.3   Sedang
147          6.5   Sedang
148          6.2   Sedang
149          5.9   Sedang

[150 rows x 2 columns]

In [12]:
#jumlah data Sepal Length berdasarkan kategori
jumlahdt_kategori_panjangsepal_ew

Sedang     71
Pendek     59
Panjang    20
Name: sepal.length, dtype: int64

In [13]:
#jumlah data Sepal Length berdasarkan interval
jumlahdt_interval_panjangsepal_ew

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal.length, dtype: int64

#### Petal Width
Equal Width Intervals lebar mahkota bunga Iris

Dikelompokkan menjadi 3 kategori yaitu Kecil, Sedang, dan Lebar

In [14]:
# label kategori Petal Width
labelK = ["Kecil", "Sedang", "Lebar"]
# Untuk menghitung banyaknya kategori label Petal Width
jumlahK = len(labelK)

# untuk menghitung interval equal-width
dt_lebarpetal_ew = pd.cut(lebar_petal, jumlahK, True, labelK)
jumlahdt_kategori_lebarpetal_ew = dt_lebarpetal_ew.value_counts()
jumlahdt_interval_lebarpetal_ew = pd.cut(lebar_petal, jumlahK, True).value_counts()

In [15]:
# data dari Petal Width beserta kategorinya
df_lebarpetal_ew=pd.DataFrame(pd.concat((lebar_petal, dt_lebarpetal_ew), axis = 1))
df_lebarpetal_ew.columns = ["PetalWidth", "category"]
df_lebarpetal_ew

     PetalWidth category
0           0.2    Kecil
1           0.2    Kecil
2           0.2    Kecil
3           0.2    Kecil
4           0.2    Kecil
..          ...      ...
145         2.3    Lebar
146         1.9    Lebar
147         2.0    Lebar
148         2.3    Lebar
149         1.8    Lebar

[150 rows x 2 columns]

In [16]:
#jumlah data Petal Width berdasarkan kategori
jumlahdt_kategori_lebarpetal_ew

Sedang    54
Kecil     50
Lebar     46
Name: petal.width, dtype: int64

In [17]:
#jumlah data Petal Width berdasarkan interval
jumlahdt_interval_lebarpetal_ew

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal.width, dtype: int64

#### Petal Length
Equal Length Intervals panjang mahkota bunga Iris

Dikelompokkan menjadi 3 kategori yaitu Pendek, Sedang, dan Panjang

In [18]:
# label kategori Petal Length
labelK = ["Pendek", "Sedang", "Panjang"]
# Untuk menghitung banyaknya kategori label Petal Length
jumlahK = len(labelK)

# untuk menghitung interval equal-length
dt_panjangpetal_ew = pd.cut(panjang_petal, jumlahK, True, labelK)
jumlahdt_kategori_panjangpetal_ew = dt_panjangpetal_ew.value_counts()
jumlahdt_interval_panjangpetal_ew = pd.cut(panjang_petal, jumlahK, True).value_counts()

In [19]:
# data dari Petal Length beserta kategorinya
df_panjangpetal_ew=pd.DataFrame(pd.concat((panjang_petal, dt_panjangpetal_ew), axis = 1))
df_panjangpetal_ew.columns = ["PetalLength", "category"]
df_panjangpetal_ew

     PetalLength category
0            1.4   Pendek
1            1.4   Pendek
2            1.3   Pendek
3            1.5   Pendek
4            1.4   Pendek
..           ...      ...
145          5.2  Panjang
146          5.0  Panjang
147          5.2  Panjang
148          5.4  Panjang
149          5.1  Panjang

[150 rows x 2 columns]

In [20]:
#jumlah data Petal Length berdasarkan kategori
jumlahdt_kategori_panjangpetal_ew

Sedang     54
Pendek     50
Panjang    46
Name: petal.length, dtype: int64

In [21]:
#jumlah data Petal Length berdasarkan interval
jumlahdt_interval_panjangpetal_ew

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal.length, dtype: int64

### Equal Frequency Intervals

Equal frequency intervals adalah discretization yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar. Fungsi qcut digunakan untuk mencari interval menggunakan metode Equal Frequency Intervals

#### Sepal Width
Equal Frequency Intervals lebar kelopak bunga Iris

Dikelompokkan menjadi 3 kategori yaitu Kecil, Sedang, dan Lebar

In [22]:
# label kategori Sepal Width
labelK = ["Kecil", "Sedang", "Lebar"]
# Untuk menghitung banyaknya kategori label Sepal Width
jumlahk = len(labelK)

# untuk menghitung interval equal-frequency
dt_lebarsepal_ef = pd.qcut(lebar_sepal, jumlahK, labelK)
jumlahdt_kategori_lebarsepal_ef = dt_lebarsepal_ef.value_counts()
jumlahdt_interval_lebarsepal_ef = pd.qcut(lebar_sepal, jumlahK).value_counts()

In [23]:
# data dari Sepal Width beserta kategorinya
df_lebarsepal_ef=pd.DataFrame(pd.concat((lebar_sepal, dt_lebarsepal_ef), axis = 1))
df_lebarsepal_ef.columns = ["SepalWidth", "category"]
df_lebarsepal_ef

     SepalWidth category
0           3.5    Lebar
1           3.0   Sedang
2           3.2   Sedang
3           3.1   Sedang
4           3.6    Lebar
..          ...      ...
145         3.0   Sedang
146         2.5    Kecil
147         3.0   Sedang
148         3.4    Lebar
149         3.0   Sedang

[150 rows x 2 columns]

In [24]:
#jumlah data Sepal Width berdasarkan kategori
jumlahdt_kategori_lebarsepal_ef

Kecil     57
Sedang    50
Lebar     43
Name: sepal.width, dtype: int64

In [25]:
#jumlah data Sepal Width berdasarkan interval
jumlahdt_interval_lebarsepal_ef

(1.999, 2.9]    57
(2.9, 3.2]      50
(3.2, 4.4]      43
Name: sepal.width, dtype: int64

#### Petal Width
Equal Frequency Intervals lebar kelopak bunga Iris

Dikelompokkan menjadi 3 kategori yaitu Kecil, Sedang, dan Lebar

In [26]:
# label kategori Petal Width
labelK = ["Kecil", "Sedang", "Lebar"]
# Untuk menghitung banyaknya kategori label Petal Width
jumlahk = len(labelK)

# untuk menghitung interval equal-frequency
dt_lebarpetal_ef = pd.qcut(lebar_petal, jumlahK, labelK)
jumlahdt_kategori_lebarpetal_ef = dt_lebarpetal_ef.value_counts()
jumlahdt_interval_lebarpetal_ef = pd.qcut(lebar_petal, jumlahK).value_counts()

In [27]:
# data dari Petal Width beserta kategorinya
df_lebarpetal_ef=pd.DataFrame(pd.concat((lebar_petal, dt_lebarpetal_ef), axis = 1))
df_lebarpetal_ef.columns = ["PetalWidth", "category"]
df_lebarpetal_ef

     PetalWidth category
0           0.2    Kecil
1           0.2    Kecil
2           0.2    Kecil
3           0.2    Kecil
4           0.2    Kecil
..          ...      ...
145         2.3    Lebar
146         1.9    Lebar
147         2.0    Lebar
148         2.3    Lebar
149         1.8    Lebar

[150 rows x 2 columns]

In [28]:
#jumlah data Petal Width berdasarkan kategori
jumlahdt_kategori_lebarpetal_ef

Sedang    52
Kecil     50
Lebar     48
Name: petal.width, dtype: int64

In [29]:
#jumlah data Petal Width berdasarkan interval
jumlahdt_interval_lebarpetal_ef

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal.width, dtype: int64

#### Sepal Length
Equal Frequency Intervals panjang kelopak bunga Iris

Dikelompokkan menjadi 3 kategori yaitu Pendek, Sedang, dan Panjang

In [30]:
# label kategori Sepal Length
labelK = ["Pendek", "Sedang", "Panjang"]
# Untuk menghitung banyaknya kategori label Sepal Length
jumlahk = len(labelK)

# untuk menghitung interval equal-frequency
dt_panjangsepal_ef = pd.qcut(panjang_sepal, jumlahK, labelK)
jumlahdt_kategori_panjangsepal_ef = dt_panjangsepal_ef.value_counts()
jumlahdt_interval_panjangsepal_ef = pd.qcut(panjang_sepal, jumlahK).value_counts()

In [31]:
# data dari Sepal Length beserta kategorinya
df_panjangsepal_ef=pd.DataFrame(pd.concat((panjang_sepal, dt_panjangsepal_ef), axis = 1))
df_panjangsepal_ef.columns = ["SepalLength", "category"]
df_panjangsepal_ef

     SepalLength category
0            5.1   Pendek
1            4.9   Pendek
2            4.7   Pendek
3            4.6   Pendek
4            5.0   Pendek
..           ...      ...
145          6.7  Panjang
146          6.3   Sedang
147          6.5  Panjang
148          6.2   Sedang
149          5.9   Sedang

[150 rows x 2 columns]

In [32]:
#jumlah data Sepal Length berdasarkan kategori
jumlahdt_kategori_panjangsepal_ef

Sedang     56
Pendek     52
Panjang    42
Name: sepal.length, dtype: int64

In [33]:
#jumlah data Sepal Length berdasarkan interval
jumlahdt_interval_panjangsepal_ef

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal.length, dtype: int64

#### Petal Length
Equal Frequency Intervals panjang kelopak bunga Iris

Dikelompokkan menjadi 3 kategori yaitu Pendek, Sedang, dan Panjang

In [34]:
# label kategori Petal Length
labelK = ["Pendek", "Sedang", "Panjang"]
# Untuk menghitung banyaknya kategori label Petal Length
jumlahk = len(labelK)

# untuk menghitung interval equal-frequency
dt_panjangpetal_ef = pd.qcut(panjang_petal, jumlahK, labelK)
jumlahdt_kategori_panjangpetal_ef = dt_panjangpetal_ef.value_counts()
jumlahdt_interval_panjangpetal_ef = pd.qcut(panjang_petal, jumlahK).value_counts()

In [35]:
# data dari Petal Length beserta kategorinya
df_panjangpetal_ef=pd.DataFrame(pd.concat((panjang_petal, dt_panjangpetal_ef), axis = 1))
df_panjangpetal_ef.columns = ["PetalLength", "category"]
df_panjangpetal_ef

     PetalLength category
0            1.4   Pendek
1            1.4   Pendek
2            1.3   Pendek
3            1.5   Pendek
4            1.4   Pendek
..           ...      ...
145          5.2  Panjang
146          5.0  Panjang
147          5.2  Panjang
148          5.4  Panjang
149          5.1  Panjang

[150 rows x 2 columns]

In [36]:
#jumlah data Petal Length berdasarkan kategori
jumlahdt_kategori_panjangpetal_ef

Sedang     54
Pendek     50
Panjang    46
Name: petal.length, dtype: int64

In [37]:
#jumlah data Petal Length berdasarkan interval
jumlahdt_interval_panjangpetal_ef

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal.length, dtype: int64

## Entropi
Entropi adalah nilai informasi yang menyatakan
ukuran ketidakpastian(impurity) dari atribut dari
suatu kumpulan obyek data dalam satuan bit.

$$
\begin{align*}
\displaystyle Entropy(S) &= \sum_{i=0}^{n} -phi \ log_{2} \ phi \\
Keterangan &: \\
S &= Himpunan \ dataset  \\
n &= Banyaknya \ partisi \ S \\
phi &= Proporsi \ dari \ S_{i} \ terhadap \ S
\end{align*}
$$

In [38]:
# Data yang akan digunakan
targetdata = df_lebarsepal_ew
# Label Kategori
label = ['Kecil', 'Sedang', 'Lebar']

In [39]:
#fungsi yang digunakan untuk menghitung banyak data berdasarkan kategori
def hitung_kategori(kolom_data, label, kolom, kategori):
  grup = kolom_data.groupby(kategori).count()
  jumlah_kategori = []
  for label in label:
    jumlah_kategori.append(grup.loc[label, kolom])
  return jumlah_kategori

In [40]:
hitung_kategori(targetdata, label, targetdata.columns[0], targetdata.columns[1])

[47, 88, 15]

In [41]:
#fungsi menghitung nilai entropy
def entropy(targetdata):
    all_prob = []
    for prob in targetdata:
        if (prob/sum(targetdata) != 0):
            all_prob.append(prob/sum(targetdata) * log2(prob/sum(targetdata)))
        else:
            all_prob.append(0)
    return -(sum(all_prob))

In [42]:
#fungsi yang digunakan untuk proses info D
def split(nilai,kolom_data, label, kolom, kategori):
  less_group =kolom_data[kolom_data[kolom] < nilai]
  greater_group =kolom_data[kolom_data[kolom] >= nilai]

  length_less_group = hitung_kategori(less_group, label, kolom, kategori)
  length_greater_group = hitung_kategori(greater_group, label, kolom, kategori)

  return (length_less_group, length_greater_group)

### Info

$$ Info_A(D) = \frac{|D_1|}{|D|} Entropy (D_1)\frac{|D_2|}{|D|}+ Entropy (D_2)$$

In [43]:
# fungsi menghitung nilai info
def info(d, targetdata):
    temp = []
    for value in d:
        temp.append((sum(value) / targetdata.shape[0]) * entropy(value))
    return sum(temp)

In [44]:
# fungsi menghitung nilai gain
def gain(inisial, new):
  return inisial - new

In [45]:
d = hitung_kategori(targetdata, label, targetdata.columns[0], targetdata.columns[1])
Einisial = entropy(d)
Einisial

1.3081585744754882